#!/bin/bash
set -e

cd ~/.cache/

git clone "https://github.com/kiro-r/rwi"
cd ./rwi

mkdir -p ~/.config/hypr/custom/scripts

cp -r ./rwi.json ~/.config/
cp -r ./rwi.py ~/.config/hypr/custom/scripts/

echo -e "\033[32mPlease edit ~/.config/rwi.json\033[0m"

sudo cp -r ./rwi.bash /usr/bin/
sudo chmod +x /usr/bin/rwi.bash

sudo cp -r ./rwi.service ~/.config/systemd/user/

echo -e "RWI installed"

cd ..
sudo rm -r ~/.cache/rwi